"""Add user and destination locations to Order model

Revision ID: 6e159ef76463
Revises: 
Create Date: 2024-11-26 23:37:45.659267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e159ef76463'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('loaders', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('user_lat', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('user_lng', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('dest_lat', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('dest_lng', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('time', sa.String(length=100), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('price')
        batch_op.drop_column('from_latitude')
        batch_op.drop_column('from_location')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('to_location')
        batch_op.drop_column('to_longitude')
        batch_op.drop_column('from_longitude')
        batch_op.drop_column('to_latitude')
        batch_op.drop_column('loader_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loader_number', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('to_latitude', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('from_longitude', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('to_longitude', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('to_location', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('from_location', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('from_latitude', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('time')
        batch_op.drop_column('dest_lng')
        batch_op.drop_column('dest_lat')
        batch_op.drop_column('user_lng')
        batch_op.drop_column('user_lat')
        batch_op.drop_column('total_cost')
        batch_op.drop_column('loaders')
        batch_op.drop_column('vehicle_type')

    # ### end Alembic commands ###
