"""second  migration

Revision ID: ce610ea2f56d
Revises: 467e82965cd5
Create Date: 2024-11-13 23:04:04.742117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce610ea2f56d'
down_revision = '467e82965cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customers_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_vehicles_customers_id", 'customers', ['customers_id'], ['id'])
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint("fk_vehicles_customers_id", type_='foreignkey')
        batch_op.drop_column('customers_id')

    # ### end Alembic commands ###
