"""Changes to driver schema

Revision ID: e1c8db5f57fe
Revises: 27f0bf42a1e9
Create Date: 2024-11-27 20:42:36.567435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c8db5f57fe'
down_revision = '27f0bf42a1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('car_type', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('_password_hash', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('license_number', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('id_number', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('license_plate', sa.String(length=100), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_drivers_phone', ['phone'])
        batch_op.drop_column('id_no')
        batch_op.drop_column('latitude')
        batch_op.drop_column('created_at')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('driver_base')
        batch_op.drop_column('driving_license_no')
        batch_op.drop_column('longitude')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('driver_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('driver_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('driver_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('driver_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('driving_license_no', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('driver_base', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('id_no', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('license_plate')
        batch_op.drop_column('id_number')
        batch_op.drop_column('license_number')
        batch_op.drop_column('_password_hash')
        batch_op.drop_column('car_type')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
